name: blast-binderized
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  #- qgrid 
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  - seaborn
  - statsmodels
  - biopython
  - regex
  - blast>=2.7.1
  - perl=5.22.0.1
  - perl-carp=1.38
  - perl-clone=0.38
  - perl-config-general=2.61
  - perl-pathtools=3.73
  - perl-data-dumper=2.161
  - perl-digest-md5=2.52
  - perl-file-temp=0.2304
  - perl-findbin=1.51
  - perl-font-ttf=1.05
  - perl-gd=2.56
  - perl-getopt-long=2.50
  - perl-io-all=0.86
  - perl-list-moreutils=0.428
  - perl-list-util=1.38
  - perl-math-bezier=0.01
  - perl-math-round=0.07
  - perl-math-vecstat=0.08
  - perl-memoize=1.03
  - perl-posix=1.38_03
  - perl-params-validate=1.26
  - perl-pod-usage=1.69
  - perl-readonly=1.04
  - perl-regexp-common=2016060801
  - perl-svg=2.64
  - perl-set-intspan=1.19
  - perl-statistics-basic=1.6611
  - perl-text-balanced=2.03
  - perl-text-format=0.59
  - perl-time-hires=1.9728
  - perl-parse-recdescent
  - perl-findbin 
  - papermill
  - plotly
